from langgraph.graph import StateGraph, START, END  
from langgraph.types import Send

from src.state import GraphState
from src.nodes.loader import loader_node
from src.nodes.analyzer import analyzer_node
from src.nodes.summarizer import worker_node
from src.nodes.reviewer import reviewer_node
from src.nodes.compile import compile_node


def assign_workers(state: GraphState):
    """Assign worker nodes based on the plan generated by the analyzer."""
    return [
        Send(
            "worker",
            {
                "paper_id": state["paper_id"],   
                "task": t,                         
            },
        )
        for t in state.get("plan", [])
    ]


def build_graph():
    """Builds the research analysis graph with defined nodes and edges.
    The graph has langgraph parallel fan in-out structure"""
    builder = StateGraph(GraphState)

    builder.add_node("loader", loader_node)
    builder.add_node("analyzer", analyzer_node)
    builder.add_node("worker", worker_node)
    builder.add_node("reviewer", reviewer_node)
    builder.add_node("compile", compile_node)

    builder.add_edge(START, "loader")
    builder.add_edge("loader", "analyzer")

    builder.add_conditional_edges("analyzer", assign_workers, ["worker"])

    builder.add_edge("worker", "reviewer")
    builder.add_edge("reviewer", "compile")
    builder.add_edge("compile", END)

    return builder.compile()